name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/web-test

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get project name from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            $DOCKER_IMAGE:latest
            $DOCKER_IMAGE:${{ steps.get_version.outputs.VERSION }}